AWSTemplateFormatVersion: 2010-09-09
Description: A simple S3 bucket creation template.
# Resources section
Resources:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
  S3Bucket: 
    Type: AWS::S3::Bucket
    #AWS will generate a bucketname for us
